MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Models/ViewModels/AdminViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVC.Models.ViewModels
{
    public class AdminViewModel
    {
        //Kullanıcı adı, şifre ve beni hatırla propertyleri tanımla. statik değil. statik değerler AdminController'da olacak. Çünkü sabit bir degere attirbute vermek mantıklı değil.
        [Required]
        public string Username { get; set; }

        [Required]
        public string Password { get; set; }

        public bool RememberMe { get; set; }

    }
}

MVC/Models/ViewModels/Product.cs
namespace MVC.Models.ViewModels
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MVC/Models/ViewModels/StudentViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models.ViewModels
{
    public class StudentViewModel
    {
        [Required(ErrorMessage ="Bu alan boş geçilemez")]
        [DisplayName("Ad Soyad")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Bu alan boş geçilemez")]
        [EmailAddress(ErrorMessage ="E-potsa formatı doğru değildir")]
        [DisplayName("E-mail")]
        public string Email { get; set; }

        [Required(ErrorMessage ="Bu alan boş geçilemez")]
        [Range(18, 60, ErrorMessage = "Yaş 18 ile 60 arasında olmalıdır")]
        [DisplayName("Yaş")]
        public int? Age { get; set; }

    }
}

MVC/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models.ViewModels;
using Microsoft.AspNetCore.Http;

namespace MVC.Controllers
{
    public class AdminController : Controller
    {
        // Admin ve parola sabit property tanımladık.
        private static string Admin = "admin";
        private static string Password = "123";

        // Giriş işlemi için POST metodu oluşturuldu.
        [HttpPost]
        public IActionResult Login(AdminViewModel model) //AdminViewModel post edildi parametre olarak alındı.
        {
            if (!ModelState.IsValid)
            {
                //Attiribute ile doğrulama vardı ama Redirect yaparken ModelState kayboluyor. O yüzden TempData kullanıldı.
                TempData["LoginError"] = "Kullanıcı adı veya şifre boş bırakılamaz.";
                return RedirectToAction("Index", "Home");
            }
            //Kullanıcıdan gelen bilgiler sabitlerle karşılaştırıldı.
            if (model.Username == Admin && model.Password == Password)
            {
                //Giriş başarılı ise cookie oluşturuldu.
                CookieOptions cookieOptions = new CookieOptions
                {
                    HttpOnly = true,
                    IsEssential = true,
                };
                // RememberMe seçeneği işaretlendiyse cookie süresi uzatıldı.
                if (model.RememberMe)
                {
                    cookieOptions.Expires = DateTimeOffset.UtcNow.AddMinutes(60);
                }
                // Cookie eklendi.
                Response.Cookies.Append("admin", model.Username, cookieOptions);

                return RedirectToAction("Index", "Home");
            }

            //TempData ile hata mesajı gönderildi.
            TempData["LoginError"] = "Kullanıcı adı veya şifre hatalı.";
            return RedirectToAction("Index", "Home");
        }

        // Çıkış işlemi için POST metodu oluşturuldu.
        [HttpPost]
        public IActionResult Logout()
        {
            // Cookie silme işlemi
            Response.Cookies.Delete("admin");
            return RedirectToAction("Index", "Home");
        }
    }
}

MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models.ViewModels;

namespace MVC.Controllers
{
    public class ProductController : Controller
    {
        private static List<Product> _products = new List<Product>
        {
            new Product {Id= 1, Name = "Kamp Çadırı" },
            new Product {Id= 2, Name = "Uyku Tulumu" },
            new Product {Id= 3, Name = "Kamp Matı" },
            new Product {Id= 4, Name = "Kamp Sandalyesi" },
            new Product {Id= 5, Name = "Paslanmaz Çelik Termos" },
            new Product {Id= 6, Name = "Batonlar" },
            new Product {Id= 7, Name = "Kayak Ayakkabıları" },
            new Product {Id= 8, Name = "Kayak Giysileri" },
            new Product {Id= 9, Name = "Kayak Gözlükleri" },
            new Product {Id= 10, Name = "Kayaklar" },
            new Product {Id= 11, Name = "Trekking Bot" },
            new Product {Id= 12, Name = "Kask" },
            new Product {Id= 13, Name = "Karabina" },
            new Product {Id= 14, Name = "Şişme Bot" },
            new Product {Id= 15, Name = "Palet" },
        };
        private static int _idCounter = 16;

        #region READ 
        public IActionResult Index()
        {
            string adminCookie = Request.Cookies["admin"];
            if (string.IsNullOrEmpty(adminCookie))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(_products);

        }
        #endregion

        #region CREATE
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Product model)
        {
            model.Id = _idCounter++;
            _products.Add(model);
            return RedirectToAction("Index");
        }
        #endregion

        #region UPDATE
        [HttpGet]
        public IActionResult Update(int id)
        {
            var product = _products.FirstOrDefault(p => p.Id == id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Update(Product model)
        {
            var product = _products.FirstOrDefault(p => p.Id == model.Id);
            if (product != null)
            {
                product.Name = model.Name;
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region DELETE
        public IActionResult Delete(int id)
        {
            var product = _products.FirstOrDefault(p => p.Id == id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Delete(Product model)
        {
            var product = _products.FirstOrDefault(p => p.Id == model.Id);
            if (product != null)
            {
                _products.Remove(product);
            }
            return RedirectToAction("Index");
            
        }
        #endregion
    }
}

MVC/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models.ViewModels;

namespace MVC.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudentViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

MVC/Views/Home/ForAdminButtonPartial.cshtml
@{
    string adminUsername = Context.Request.Cookies["admin"];
    @if(adminUsername != null)
    {
        <a class="btn btn-dark" asp-controller="Product" asp-action="Index" aspdata-bs-toggle="collapse" style="color: white;" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Ürün Listesi (Admin)</a>
        <a class="btn btn-dark" asp-controller="Student" asp-action="Create" aspdata-bs-toggle="collapse" style="color: white;" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Müşteri (Admin)</a>
    }   
}

MVC/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Celebi Outdoor Sports";
}
<p>
<p class="d-flex justify-content-center gap-3">
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" aria-expanded="false" aria-controls="multiCollapseExample1">Erkek</a>
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Kadın</a>
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Çocuk</a>
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Kamp</a>
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Kayak</a>
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Dağcılık</a>
	<!--Partial View Kullanıldı Müşteri Butonu Ve Ürünler Listesi Oturum Kontrolüne göre admin ise gösterilecek-->
	<partial name="ForAdminButtonPartial"/>
</p>

<div id="carouselExample" class="carousel slide m-1">
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src="~/images/kamp.png" class="d-block w-100" style="height: 750px; object-fit: cover;">
		</div>
		<div class="carousel-item">
			<img src="~/images/kayak.png" class="d-block w-100" style="height: 750px; object-fit: cover;">
		</div>
		<div class="carousel-item">
			<img src="~/images/dagcilik.png" class="d-block w-100" style="height: 750px; object-fit: cover;">
		</div>
	</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Previous</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Next</span>
	</button>
</div>

<p>
<p class="d-flex justify-content-center gap-5">
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" aria-expanded="false" aria-controls="multiCollapseExample1">Yeni Ürünler</a>
	<a class="btn btn-dark" data-bs-toggle="collapse" style="color: white;" data-bs-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">Popüler Ürünler</a>
</p>

<div class="d-flex justify-content-center gap-5">
	<div class="card" style="width: 18rem;">
		<img src="~/images/cadır.webp" class="card-img-top" alt="...">
		<div class="card-body">
			<p class="card-text">HUSKY BOLEN YESIL 4 DURAL KISILIK CADIR <br /><strong>21.999 TL</strong></p>
		</div>
	</div>
	<div class="card" style="width: 18rem;">
		<img src="~/images/gozluk.webp" class="card-img-top" alt="...">
		<div class="card-body">
			<p class="card-text">OAKLEY TARGET LINE L SNOW GOGGLES UNISEX KAYAK GÖZLÜĞÜ	<br /><strong>3.999 TL</strong> </p>
		</div>
	</div>
	<div class="card" style="width: 18rem;">
		<img src="~/images/palet.webp" class="card-img-top" alt="...">
		<div class="card-body">
			<p class="card-text">BEUCHAT Palet Açık AQUABIONIC EVO<br /><strong>8.999 TL</strong></p>
		</div>
	</div>
</div>

MVC/Views/Product/Create.cshtml
@using MVC.Models.ViewModels

@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container text-center">
	<h1>Ürün Ekle</h1>
</div>

@model Product

<form method="post">
	<div class="container text-center">
		<div class="row">
			<div class="col-8">
				<div class="row g-3 align-items-center">
					<div class="mb-3">
						<label for="exampleInputPassword1" class="visually-hidden">Ürün Adı</label>
						<input asp-for="Name" class="form-control" placeholder="Ürün Adı">
					</div>
				</div>
			</div>
			<div class="col-4">
				<button type="submit" class="btn btn-dark">Ürünü Kaydet</button>
			</div>
		</div>
	</div>
</form>

MVC/Views/Product/Delete.cshtml
@using MVC.Models.ViewModels

@{
	ViewData["Title"] = "Ürün Sil";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Product

<div class="container text-center">
	<h1>Ürün Sil</h1>
</div>
<p><a href="/Product" class="btn btn-dark">Geri Dön</a></p>

<form method="post" class="row g-3">
	<input type="hidden" asp-for="Id" />
	<p>
		<div class="row">

			<div class="alert alert-danger" role="alert">
				<strong>@Model.Name</strong> isimli ürünü silmek istediğinize emin misiniz?
			</div>

			<div class="container text-center">
				<button type="submit" class="btn btn-danger">Ürünü Sil</button>
			</div>
		</div>

	</p>

</form>

MVC/Views/Product/Index.cshtml
@using MVC.Models.ViewModels
@model List<Product>
@{
	ViewData["Title"] = "Ürün Listesi";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container text-center">
	<h1>Admin Paneline Hoşgeldin Alper Çelebi</h1>
	<p><h1>Ürün Listesi</h1></p>
</div>

<p><a class="btn btn-dark" asp-controller="Product" asp-action="Create">Ürün Ekle</a></p>

<table class="table">
	<thead class="table-dark">
		<tr>
			<th scope="col">Id</th>
			<th scope="col">Ürün Adı</th>
			<th scope="col">İşlem</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var product in Model)
		{
			<tr>
				<td>@product.Id</td>
				<td>@product.Name</td>
				<td>
					<a href="/Product/Update/@product.Id" class="btn btn-dark">Güncelle</a>
					<a href="/Product/Delete/@product.Id" class="btn btn-danger">Sil</a>
				</td>
			</tr>
		}
	</tbody>
</table>

MVC/Views/Product/Update.cshtml
@using MVC.Models.ViewModels

@{
    ViewData["Title"] = "Ürün Güncelle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container text-center">
	<h1>Ürün Güncelle</h1>
</div>

@model Product

<form method="post">
	<div class="container text-center">
		<div class="row">
			<div class="col-8">
				<div class="row g-3 align-items-center">
					<div class="mb-3">
						<input type="hidden" asp-for="Id" />
						<label for="exampleInputPassword1" class="visually-hidden">Ürün Adı</label>
						<input asp-for="Name" class="form-control" placeholder="Ürün Adı">
					</div>
				</div>
			</div>
			<div class="col-4">
				<button type="submit" class="btn btn-dark">Ürünü Güncelle</button>
			</div>
		</div>
	</div>
</form>

MVC/Views/Shared/_AdminLoginPartial.cshtml
@model MVC.Models.ViewModels.AdminViewModel
@*AdminViewModel'i layouta bağlayınca program hata verdiği için partial view yapıldı. kullanılaca form ve kontroller buraya taşındı. Layoutta çağıralacak*@
@{
	@if (TempData["LoginError"] != null)
	{
		// TempData boş değilse (yani Controller'dan bir hata mesajı gelmişse)
		<div class="alert alert-danger mb-2" role="alert">
			@TempData["LoginError"]
		</div>
	}
	// Cookie'de "admin" adındaki cookie'ye değer atandı
	string adminUsername = Context.Request.Cookies["admin"];

	//Cookie'de admin degeri bos degilse admin girişi yapılmış demektir
	@if (adminUsername != null)
	{
		// Giriş yapılmışsa görünecek kısım
		<div class="d-flex align-items-center gap-2" style="color: white;">
			<span>Merhaba Alper</span>

			@* Buraya Logout Aksiyonunu tetikleyecek Form gelecek *@
			<form asp-controller="Admin" asp-action="Logout" method="post">
				<button type="submit" class="btn btn-danger btn-sm">Çıkış</button>
			</form>
		</div>
	}
	else
	{
		// Giriş yapılmamışsa, formun görünecek kısmı
		<form method="post" asp-controller="Admin" asp-action="Login" class="d-flex flex-column">
			<div class="d-flex align-items-center gap-2 mb-1">
				<input asp-for="Username" type="text" class="form-control form-control-sm" placeholder="Kullanıcı Adı" aria-label="Kullanıcı Adı" style="width: 150px;">

				<input asp-for="Password" type="password" class="form-control form-control-sm" placeholder="Parola" aria-label="Parola" style="width: 120px;">

				<button type="submit" class="btn btn-secondary">Giriş</button>
			</div>

			<div class="form-check m-0 align-self-start">
				<input type="checkbox" asp-for="RememberMe" class="form-check-input" id="rememberMe">
				<label class="form-check-label" for="rememberMe" style="color: white; font-size: 0.8rem;">Beni Hatırla</label>
			</div>
		</form>
	}
}

MVC/Views/Shared/_Layout.cshtml
@using MVC.Models.ViewModels
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MVC</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar bg-body-tertiary bg-dark" style="color: white;">
			<div class="container-fluid d-flex gap-3 align-items-center">
				<a class="navbar-brand" asp-controller="Home" asp-action="Index" style="color: white;">Celebi Outdoor Sports</a>

				<form class="d-flex gap-2 me-auto" role="search">
					<input class="form-control" type="search" style="color: white; width: 350px;" placeholder="Arama" aria-label="Arama" />
					<button class="btn btn-outline-success" style="color: white;" type="submit">Arama</button>
				</form>
				<!--partial view kullanarak AdminLoginPartial.cshtml'deki formu buraya çağırdık -->
				<partial name="_AdminLoginPartial" model="new MVC.Models.ViewModels.AdminViewModel()" />
				
			</div>
		</nav>
	</header>

	<!--SLIDER-->
	<main role="main" class="pb-3">
		@RenderBody()
	</main>

	<!--FOOTER-->
	<footer class="border-top footer text-muted">
		<div class="container d-flex flex-wrap justify-content-between align-items-center">
			<p class="col-md-4 mb-0 text-white"></p>
			<ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
				<li class="ms-3">
					<a href="#">
						<img src="~/images/instagram.png" width="35" height="35" class="footer-icon" alt="Instagram" />
					</a>
				</li>
				<li class="ms-3">
					<a href="#">
						<img src="~/images/facebook.png" width="35" height="35" class="footer-icon" alt="Facebook" />
					</a>
				</li>
			</ul>
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC/Views/Student/Create.cshtml
@using MVC.Models.ViewModels

@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
@model StudentViewModel

<div class="container text-center">
	<h1>Admin Paneline Hoşgeldin Alper Çelebi</h1>
	<p><h1>Müşteri Ekle</h1></p>
</div>

<form method="post">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="container text-center">
		<div class="form-group container text-center col-3">
		<label asp-for="Name" class="control-label d-flex"></label>
		<input asp-for="Name" class="form-control" />
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>
		<div class="form-group container text-center col-3">
			<label asp-for="Email" class="control-label d-flex"></label>
		<input asp-for="Email" class="form-control" />
		<span asp-validation-for="Email" class="text-danger"></span>
	</div>
		<div class="form-group container text-center col-3">
			<label asp-for="Age" class="control-label d-flex"></label>
		<input asp-for="Age" class="form-control" />
		<span asp-validation-for="Age" class="text-danger"></span>
	</div>
	<br />
	<div class="form-group">
		<input type="submit" value="Kaydet" class="btn btn-dark" />
	</div>
	</div>
</form>